name: evefrontier_index_module_client
description: Modular tools and analytics for the EVE Frontier universe. Reputation systems, player metrics, and community infrastructure — built with Dart.
version: 0.0.1
homepage: https://evefrontier.club
publish_to: none

environment:
  sdk: "^3.8.0"

dependencies:
  serverpod_client: ^3.4.2
